### PR TITLE
Bumps project to bevy 0.11

### PR DESCRIPTION
**Pull request by naomijub**
Bumps bevy to 0.11 and bevy_rapier to 0.22

I can do bevy 0.12 as soon as rapier has merged their changes and I finished my stuff.
Nice workaround for bevy-inspector

### CODE REVIEW

**Comment by naomijub** [comment]
Github actions can be found here: https://github.com/naomijub/bevy_mod_component_mirror/pull/1

**Comment by naomijub** [comment]
@nicopap ?

**Comment by nicopap** [comment]
oh my god I completely missed this PR. Thank you so much!

You did well to ping me. I'll get it merged quickly.

**Comment by nicopap** [comment]
Merged through e13f1dd0f0213f8bbef39d8f365f431bab4a2169

Thank you for your contribution! And sorry for not reacting faster

**Pull request closed without merging**
